# wvsR
## Codebook Functions

# Generated from data/ assets. Rebuild only when upstream joint files change.
.wvs_codebook <-
structure(list(label = c("Study", "Wave", "Version of Joint Data File", 
"Version of EVS5 and WVS7 source data files", "Digital Object Identifier (GESIS doi)", 
"Digital Object Identifier (WVSA doi)", "Source of the Joint dataset", 
"Unified respondent number (Joint)", "Interviewer number", "Country (ISO 3166-1 Numeric code)", 
"Country (ISO 3166-1 Alpha-2 code)", "Country (CoW Numeric code)", 
"Year survey", "Year/month of start-fieldwork", "Year/month of end-fieldwork", 
"Country - year", "Mode of data collection", "Mixed mode/matrix design (EVS5)", 
"Mode of data collection (follow-up) (EVS5)", "Matrix attribution (group/variable bloc) (EVS5)", 
"Year/month of start-fieldwork (matrix design) (EVS5)", "Year/month of end-fieldwork (matrix design) (EVS5)", 
"Survey year (follow-up) (EVS5)", "Total length of interview", 
"Time of the interview - Start [hh.mm]", "Time of the interview - End [hh.mm]", 
"Date interview [YYYYMMDD]", "Date of interview (follow-up) (EVS5)", 
"Time of the interview -Start (constructed) (follow-up) (EVS5)", 
"Time of the interview -End (constructed) (follow-up) (EVS5)", 
"Language of interview (WVS/EVS list of languages)", "Language of interview (ISO 639-1 alpha-2 / 639-2 alpha-3)", 
"Weight", "Population size weight", "Equilibrated weight-1000", 
"Region where the interview was conducted (NUTS-1)", "Region where the interview was conducted (NUTS-2)", 
"Region where the interview was conducted (ISO)", "Size of town where interview was conducted (5 categories)", 
"Respondent interested during the interview", "Important in life: Family", 
"Important in life: Friends", "Important in life: Leisure time", 
"Important in life: Politics", "Important in life: Work", "Important in life: Religion", 
"Feeling of happiness", "State of health (subjective)", "Satisfaction with your life", 
"How much freedom of choice and control", "Important child qualities: good manners", 
"Important child qualities: independence", "Important child qualities: hard work", 
"Important child qualities: feeling of responsibility", "Important child qualities: imagination", 
"Important child qualities: tolerance and respect for other people", 
"Important child qualities: thrift saving money and things", 
"Important child qualities: determination perseverance", "Important child qualities: religious faith", 
"Important child qualities: unselfishness", "Important child qualities: obedience", 
"Member: Belong to religious organization", "Member: Belong to education, arts, music or cultural activities", 
"Member: Belong to labour unions", "Member: Belong to political parties", 
"Member: Belong to conservation, the environment, ecology, animal rights", 
"Member: Belong to professional associations", "Member: Belong to sports or recreation", 
"Member: Belong to consumer groups", "Member: Belong to other groups", 
"Member: Belong to humanitarian or charitable organization", 
"Member: Belong to self-help group, mutual aid group", "Neighbours: People of a different race", 
"Neighbours: Heavy drinkers", "Neighbours: Immigrants/foreign workers", 
"Neighbours: Drug addicts", "Neighbours: Homosexuals", "Most people can be trusted", 
"Protecting environment vs. Economic growth", "Jobs scarce: Men should have more right to a job than women (3-point scale)", 
"Jobs scarce: Men should have more right to a job than women (5-point scale)", 
"Jobs scarce: Employers should give priority to (nation) people than immigrants (", 
"Jobs scarce: Employers should give priority to (nation) people than immigrants (", 
"Homosexual couples are as good parents as other couples", "Duty towards society to have children", 
"It is childs duty to take care of ill parent", "People who donÃ‚Â´t work turn lazy", 
"Work is a duty towards society", "Work should come first even if it means less spare time", 
"Trust: Your family (B)", "Trust: Your neighborhood (B)", "Trust: People you know personally (B)", 
"Trust: People you meet for the first time (B)", "Trust: People of another religion (B)", 
"Trust: People of another nationality (B)", "One of main goals in life has been to make my parents proud", 
"Men make better political leaders than women do", "University is more important for a boy than for a girl", 
"Pre-school child suffers with working mother", "Men make better business executives than women do", 
"Aims of country: first choice", "Aims of country: second choice", 
"Aims of respondent: first choice", "Aims of respondent: second choice", 
"Post-Materialist index 4-item", "Willingness to fight for country", 
"Future changes: Less importance placed on work", "Future changes: Greater respect for authority", 
"Interest in politics", "Political action: signing a petition", 
"Political action: joining in boycotts", "Political action: attending lawful/peaceful demonstrations", 
"Political action: joining unofficial strikes", "Self positioning in political scale", 
"Income equality", "Private vs state ownership of business", 
"Government responsibility", "Competition good or harmful", "Confidence: Churches", 
"Confidence: Armed Forces", "Confidence: The Press", "Confidence: Labour Unions", 
"Confidence: The Police", "Confidence: Parliament", "Confidence: The Civil Services", 
"Confidence: Major regional organization (combined from country-specific)", 
"Confidence: The European Union", "Confidence: The Government", 
"Confidence: The Political Parties", "Confidence: Major Companies", 
"Confidence: The Environmental Protection Movement", "Confidence: Justice System/Courts", 
"Confidence: The United Nations", "Satisfaction with the political system", 
"Political system: Having a strong leader", "Political system: Having experts make decisions", 
"Political system: Having the army rule", "Political system: Having a democratic political system", 
"Which party would you vote for: first choice (WVS7)", "Which political party appeals to you most (ISO 3166-1) (EVS5)", 
"Democracy: Governments tax the rich and subsidize the poor.", 
"Democracy: Religious authorities interpret the laws.", "Democracy: People choose their leaders in free elections.", 
"Democracy: People receive state aid for unemployment.", "Democracy: The army takes over when government is incompetent.", 
"Democracy: Civil rights protect peopleÃ¢â‚¬â„¢s liberty against oppression.", 
"Democracy: Women have the same rights as men.", "Democracy: The state makes people's incomes equal", 
"Democracy: People obey their rulers", "Importance of democracy", 
"Democraticness in own country", "Vote in elections: local level", 
"Vote in elections: National level", "How often in country's elections: Votes are counted fairly", 
"How often in country's elections: Opposition candidates are prevented from runni", 
"How often in country's elections: TV news favors the governing party", 
"How often in country's elections: Voters are bribed", "How often in country's elections: Journalists provide fair coverage of elections", 
"How often in country's elections: Election officials are fair", 
"How often in country's elections: Rich people buy elections", 
"How often in country's elections: Voters are threatened with  violence at the po", 
"Religious denomination", "How often do you attend religious services", 
"How often do you pray (WVS7)", "Pray to God outside of religious services (EVS5)", 
"Religious person", "Believe in: God", "Believe in: life after death", 
"Believe in: hell", "Believe in: heaven", "How important is God in your life", 
"Justifiable: Claiming government benefits to which you are not entitled", 
"Justifiable: Avoiding a fare on public transport", "Justifiable: Cheating on taxes", 
"Justifiable: Someone accepting a bribe", "Justifiable: Homosexuality", 
"Justifiable: Prostitution", "Justifiable: Abortion", "Justifiable: Divorce", 
"Justifiable: Euthanasia", "Justifiable: Suicide", "Justifiable: Having casual sex", 
"Justifiable: Political violence", "Justifiable: Death penalty", 
"Citizen of country", "How proud of nationality", "Evaluate the impact of immigrants on the development of [your country]", 
"How close you feel: Continent; e.g. Europe, Asia etc.", "How close you feel: World", 
"How close you feel: Your village, town or city", "How close do you feel: to your county, region, district", 
"How close do you feel: to country", "Government has the right: Keep people under video surveillance in public areas", 
"Government has the right: Monitor all e-mails and any other information exchange", 
"Government has the right: Collect information about anyone living in [COUNTRY] w", 
"Sex", "Year of birth", "Age", "Age recoded (6 intervals)", "Age recoded (3 intervals)", 
"Respondent immigrant / born in country", "Respondents country of birth: ISO 3166-1 code", 
"Respondents country of birth: ISO 3166-1/3 Alpha code", "Mother born in country", 
"Mothers country of birth: ISO 3166-1 code", "Mothers country of birth: ISO 3166-1/3 Alpha code", 
"Father born in country", "Fathers country of birth: ISO 3166-1 code", 
"Fathers country of birth: ISO 3166-1/3 Alpha code", "Marital status", 
"Do you live with your parents", "How many children do you have", 
"Number of people in household", "Highest educational level attained - Respondent: ISCEDÃ¢â‚¬\u0090code one digit", 
"Highest educational level attained - Respondent (recoded)", 
"Highest educational level attained - RespondentÃ‚Â´s Spouse: ISCED-code one digit", 
"Highest educational level attained - RespondentÃ‚Â´s Spouse (recoded)", 
"Highest educational level attained - RespondentÃ‚Â´s Mother:  ISCEDÃ¢â‚¬\u0090code one dig", 
"Highest educational level attained - RespondentÃ‚Â´s Mother (recoded)", 
"Highest educational level attained - RespondentÃ‚Â´s Father:  ISCEDÃ¢â‚¬\u0090code one dig", 
"Highest educational level attained - RespondentÃ‚Â´s Father (recoded)", 
"Employment status Respondent", "Employment status Spouse/partner", 
"Institution of occupation", "Job  profession/industry (2 digit ISCO08) - respondent (EVS5)", 
"Occupational group - respondent (WVS7)", "Occupational group - respondentÃ‚Â´s father (EVS5-main earner) (respondent 14 year", 
"Job  profession/industry (2 digit ISCO08) - respondentÃ‚Â´s spouse (EVS5)", 
"Occupational group - respondentÃ‚Â´s spouse (WVS7)", "Scale of incomes (WVS7)", 
"Scale of incomes (EVS5)"), group = c("Protocol Variables", "Protocol Variables", 
"Protocol Variables", "Protocol Variables", "Protocol Variables", "Protocol Variables", 
"Protocol Variables", "Protocol Variables", "Protocol Variables", "Protocol Variables", 
"Protocol Variables", "Protocol Variables", "Protocol Variables", "Protocol Variables", 
"Protocol Variables", "Protocol Variables", "Design Variables", "Design Variables", 
"Design Variables", "Design Variables", "Design Variables", "Design Variables", 
"Design Variables", "Protocol Variables", "Protocol Variables", 
"Protocol Variables", "Protocol Variables", "Protocol Variables", "Protocol Variables", 
"Protocol Variables", "Protocol Variables", "Protocol Variables", "Protocol Variables", 
"Protocol Variables", "Protocol Variables", "Protocol Variables", "Protocol Variables", 
"Protocol Variables", "Demographics (Respondent)", "Perceptions of life", "Perceptions of life", 
"Perceptions of life", "Perceptions of life", "Perceptions of life", "Perceptions of life", "Perceptions of life", 
"Perceptions of life", "Perceptions of life", "Perceptions of life", "Perceptions of life", "Perceptions of life", 
"Perceptions of life", "Perceptions of life", "Perceptions of life", "Perceptions of life", "Perceptions of life", 
"Perceptions of life", "Perceptions of life", "Perceptions of life", "Perceptions of life", "Perceptions of life", 
"Perceptions of life", "Perceptions of life", "Perceptions of life", "Perceptions of life", "Perceptions of life", 
"Perceptions of life", "Perceptions of life", "Perceptions of life", "Perceptions of life", "Perceptions of life", 
"Perceptions of life", "Perceptions of life", "Perceptions of life", "Perceptions of life", "Perceptions of life", 
"Perceptions of life", "Environment", "Work", "Work", "Work", 
"Work", "Family", "Family", "Family", "Work", 
"Work", "Work", "Family", "National identity", "National identity", 
"National identity", "National identity", "National identity", "Family", "Family", 
"Family", "Family", "Family", "Politics and society", "Politics and society", 
"Politics and society", "Politics and society", "Politics and society", "Politics and society", "Politics and society", 
"Politics and society", "Politics and society", "Politics and society", "Politics and society", "Politics and society", 
"Politics and society", "Politics and society", "Politics and society", "Politics and society", "Politics and society", 
"Politics and society", "Politics and society", "Politics and society", "Politics and society", "Politics and society", 
"Politics and society", "Politics and society", "Politics and society", "Politics and society", "Politics and society", 
"Politics and society", "Politics and society", "Politics and society", "Politics and society", "Politics and society", 
"Politics and society", "Politics and society", "Politics and society", "Politics and society", "Politics and society", 
"Politics and society", "Politics and society", "Politics and society", "Politics and society", "Politics and society", 
"Politics and society", "Politics and society", "Politics and society", "Politics and society", "Politics and society", 
"Politics and society", "Politics and society", "Politics and society", "Politics and society", "Politics and society", 
"Politics and society", "Politics and society", "Politics and society", "Politics and society", "Politics and society", 
"Politics and society", "Politics and society", "Politics and society", "Politics and society", "Religion and morale", 
"Religion and morale", "Religion and morale", "Religion and morale", "Religion and morale", "Religion and morale", 
"Religion and morale", "Religion and morale", "Religion and morale", "Religion and morale", "Religion and morale", 
"Religion and morale", "Religion and morale", "Religion and morale", "Religion and morale", "Religion and morale", 
"Religion and morale", "Religion and morale", "Religion and morale", "Religion and morale", "Religion and morale", 
"Politics and society", "Religion and morale", "National identity", "National identity", "National identity", 
"National identity", "National identity", "National identity", "National identity", "National identity", 
"Security", "Security", "Security", "Demographics (Respondent)", "Demographics (Respondent)", 
"Demographics (Respondent)", "Demographics (Respondent)", "Demographics (Respondent)", "National identity", "Demographics (Respondent)", 
"Demographics (Respondent)", "Demographics (Respondent's parents)", "Demographics (Respondent's parents)", "Demographics (Respondent's parents)", "Demographics (Respondent's parents)", 
"Demographics (Respondent's parents)", "Demographics (Respondent's parents)", "Demographics (Respondent)", "Demographics (Respondent)", "Demographics (Respondent)", 
"Demographics (Respondent)", "Demographics (Respondent)", "Demographics (Respondent)", "Demographics (Respondent's partner)", "Demographics (Respondent's partner)", 
"Demographics (Respondent's parents)", "Demographics (Respondent's parents)", "Demographics (Respondent's parents)", "Demographics (Respondent's parents)", "Demographics (Respondent)", 
"Demographics (Respondent's partner)", "Demographics (Respondent)", "Demographics (Respondent)", "Demographics (Respondent)", "Demographics (Respondent's parents)", 
"Demographics (Respondent's partner)", "Demographics (Respondent's partner)", "Demographics (Respondent)", "Demographics (Respondent)"), direction = c(1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, -1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 
1, 1, 1, 1, 1, -1, -1, -1, -1, 1, 1, -1, -1, -1, -1, -1, -1, 
-1, 1, -1, -1, -1, 1, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1), min = c(1, 5, 0, 0, 0, 0, 0, 8050001, 
1, 8, 0, 2, 2017, 201701, 201703, 82018, 1, 1, 1, 1, 201709, 
201712, 2017, 0, 0, 0, 20170101, 20170930, 0.01, 0.01, 2, 0, 
0.00622169007293812, 0.00684462151394422, 0.24888, 0, 0, 20002, 
-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
-1, -1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
-1, -1, -1, -1, 0, -1, -1, 0, -1, -1, 0, -1, -1, -1, -1, -1, 
-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
-1), max = c(2, 7, 0, 0, 0, 0, 0, 909070447, 97913415, 909, 0, 
920, 2023, 202306, 202307, 9092022, 6, 5, 2, 8, 201801, 201802, 
2018, 1365, 23.58, 24.59, 20230701, 20180215, 23.49, 23.58, 4092, 
0, 19.930070692, 61.8200117021277, 2.2371365, 0, 0, 909001, 5, 
3, 4, 4, 4, 4, 4, 4, 4, 5, 10, 10, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 3, 
5, 3, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
4, 4, 4, 3, 1, 3, 3, 4, 3, 3, 3, 3, 10, 10, 10, 10, 10, 4, 4, 
4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 10, 4, 4, 4, 4, 909039, 
82666, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 4, 4, 4, 4, 
4, 4, 4, 4, 4, 4, 9, 8, 8, 7, 3, 1, 1, 1, 1, 10, 10, 10, 10, 
10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 1, 4, 5, 4, 4, 4, 4, 
4, 4, 4, 4, 2, 2007, 82, 6, 3, 2, 9999, 0, 1, 9999, 0, 1, 9999, 
0, 6, 4, 5, 6, 8, 3, 8, 3, 8, 3, 8, 3, 8, 9, 3, 99, 11, 66, 99, 
11, 10, 10)), class = "data.frame", row.names = c("study", "wave", 
"version", "versn_s", "doi_gesis", "doi_wvsa", "studytit", "uniqid", 
"intrvwr_id", "cntry", "cntry_AN", "cntrycow", "year", "fw_start", 
"fw_end", "cntry_y", "mode", "mm_mixed_mode_EVS5", "mm_mode_fu_EVS5", 
"mm_matrix_group_EVS5", "mm_fw_start_fu_EVS5", "mm_fw_end_fu_EVS5", 
"mm_year_fu_EVS5", "ivlength", "ivstart", "ivstend", "ivdate", 
"mm_v277_fu_EVS5", "mm_v278a_fu_r_EVS5", "mm_v279a_fu_r_EVS5", 
"lnge_num", "lnge_iso", "gwght", "pwght", "wght_eq1000", "reg_nuts1", 
"reg_nuts2", "reg_iso", "size_5c", "respint", "A001", "A002", 
"A003", "A004", "A005", "A006", "A008", "A009", "A170", "A173", 
"A027", "A029", "A030", "A032", "A034", "A035", "A038", "A039", 
"A040", "A041", "A042", "A065", "A066", "A067", "A068", "A071", 
"A072", "A074", "A078", "A079", "A080_01", "A080_02", "A124_02", 
"A124_03", "A124_06", "A124_08", "A124_09", "A165", "B008", "C001", 
"C001_01", "C002", "C002_01", "D081", "D026_03", "D026_05", "C038", 
"C039", "C041", "D001_B", "G007_18_B", "G007_33_B", "G007_34_B", 
"G007_35_B", "G007_36_B", "D054", "D059", "D060", "D061", "D078", 
"E001", "E002", "E003", "E004", "Y002", "E012", "E015", "E018", 
"E023", "E025", "E026", "E027", "E028", "E033", "E035", "E036", 
"E037", "E039", "E069_01", "E069_02", "E069_04", "E069_05", "E069_06", 
"E069_07", "E069_08", "E069_18A", "E069_18", "E069_11", "E069_12", 
"E069_13", "E069_14", "E069_17", "E069_20", "E111_01", "E114", 
"E115", "E116", "E117", "E179_WVS7", "E181_EVS5", "E224", "E225", 
"E226", "E227", "E228", "E229", "E233", "E233A", "E233B", "E235", 
"E236", "E263", "E264", "E265_01", "E265_02", "E265_03", "E265_04", 
"E265_05", "E265_06", "E265_07", "E265_08", "F025", "F028", "F028B_WVS7", 
"F066_EVS5", "F034", "F050", "F051", "F053", "F054", "F063", 
"F114A", "F115", "F116", "F117", "F118", "F119", "F120", "F121", 
"F122", "F123", "F132", "E290", "F144_02", "G005", "G006", "G052", 
"G062", "G063", "G255", "G256", "G257", "H009", "H010", "H011", 
"X001", "X002", "X003", "X003R", "X003R2", "G027A", "X002_02A", 
"X002_02B", "V002", "V002A", "V002A_01", "V001", "V001A", "V001A_01", 
"X007", "x026_01", "X011", "X013", "X025A_01", "X025R", "W002A_01", 
"W002R", "V004AM_01", "V004RM", "V004AF_01", "V004RF", "X028", 
"W003", "X052", "X035_EVS5", "X036E_WVS7", "V097EF", "W005_EVS5", 
"W006E_WVS7", "X047_WVS7", "X047E_EVS5"))

#' Retrieve human-readable variable label(s)
#'
#' @param v Character vector of variable names.
#' List item metadata from the static EVS/WVS codebook
#'
#' @param vars Optional character vector of variable names to include.
#' @param group Optional character vector of groups to include.
#' @param columns Optional character vector of columns to return. Valid
#'   values are `"label"`, `"group"`, `"direction"`, `"min"`, and `"max"`.
#' @return Data.frame describing item metadata. Row names are variable names.
#' @export
wvs_items <- function(
  vars = NULL,
  group = NULL,
  columns = c("label", "group", "direction", "min", "max")
) {
  valid_cols <- c("label", "group", "direction", "min", "max")

  columns <- unique(columns)
  if (!all(columns %in% valid_cols)) {
    stop("columns must be one or more of: ", paste(valid_cols, collapse = ", "), call. = FALSE)
  }

  out <- .wvs_codebook

  if (!is.null(vars)) {
    out <- out[rownames(out) %in% vars, , drop = FALSE]
  }
  if (!is.null(group)) {
    out <- out[out$group %in% group, , drop = FALSE]
  }

  out[, columns, drop = FALSE]
}
